FROM node:22-slim

WORKDIR /usr/src/app

COPY package.json package-lock.json* ./
ENV DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"
RUN npm ci --include=dev --ignore-scripts

COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npx prisma generate

COPY --chown=node . .

EXPOSE 3000
USER node

CMD ["npm", "run", "dev"]
