FROM node:lts-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /usr/src/app

COPY package.json package-lock.json* ./
ENV DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"
RUN npm install --ignore-scripts

COPY prisma ./prisma
RUN npx prisma generate

COPY --chown=node . .

EXPOSE 3000
USER node

CMD ["npm", "run", "dev"]
